### ISSUE TITLE
I can run the work, but the output is so blurry even with face enhancer.

### ISSUE THREAD

**Issue by Zeelyne** [hacksider/Deep-Live-Cam#278]
Hi,
I used an uploaded image of 738  738 pixel and a target video of 512  512 pixel, 25fps.

![屏幕截图 2024-08-13 174118](https://github.com/user-attachments/assets/a3b35a14-ff71-4eba-b5e7-e28d73159d4c)

Not error was shown, but I got very very blurry result. The face was not well replaced. 
![屏幕截图 2024-08-13 174208](https://github.com/user-attachments/assets/d5d69e47-75b3-4853-8cd8-ff258612b78c)
Here is the log.
![屏幕截图 2024-08-13 174154](https://github.com/user-attachments/assets/147e4c14-d411-46f1-bf2e-797b52bff41e)

Then i compressed the uploaded image to 126  126 pixel and applied it as image, and with the same target video of 512  512 pixel, 25fps. But still, the results is slightly improved but remains very blurry. Like the image below.(Sorry if this scare you guys... the effect is not so good)

![2](https://github.com/user-attachments/assets/a64f8f9c-4d08-4050-b157-782d90fc3d96)

I think there must something wrong with my settings or installations, would you please give me some suggestions for this?
Thanks a lot!

**Comment by peytoncai** [comment]
same

**Comment by StatLee** [comment]
same

**Comment by StatLee** [comment]
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3

It works.

**Comment by Zeelyne** [comment]
Thanks!  It works!

> pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3
> 
> It works.(By NV ENV)

**Comment by Zeelyne** [comment]
Issue resolved

**Comment by xx7Ahmed7xx** [comment]
There is no version 1.16.3

**Comment by StevenCanDrink** [comment]
> There is no version 1.16.3

using python 3.10 plz

**Comment by Nenormaln1** [comment]
I had the same issue and I had a little "harder" fix.

For some reason the version 1.16.3 of onnxruntime didn't work for my GPU (Laptop RTX 4060), it just kept crashing as soon as I started Live cam with this error:

`RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.`
 
I had to install a earlier version of Cuda (11.8), and a different version of cuDNN (v8.9.7compatible with CUDA 11.X) for it to work properly.
If you had a newer version of CUDA installed, make sure to edit the path properly so that the correct version is used.


So for all the people having the same issue:
Get these:
[CUDA 11.8](https://developer.nvidia.com/cuda-11-8-0-download-archive)
[cuDNN](https://developer.nvidia.com/rdp/cudnn-archive#a-collapse858-118) 

Then just reinstall onnxruntime like above:
```
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3
```

If crashes keep happening, it could be caused by numpy, so just install this version and it should be fixed.
```
pip uninstall numpy
pip install numpy==1.26.4
```
