### ISSUE TITLE
Recommended settings

### ISSUE THREAD

**Issue by wasgehthierab** [hacksider/Deep-Live-Cam#322]
I would like to know which settings are the best to use the optimal power of my computer.
I have a m1 pro and it has 8-core CPU with 6 performance cores and 2 efficiency cores, a 14-core GPU and 16-core Neural Engine... so which of these cores is used by deep-live-cam?
What would be the optimal settings for the options?

```
  --video-encoder {libx264,libx265,libvpx-vp9}             adjust output video encoder
  --video-quality [0-51]                                   adjust output video quality
  --max-memory MAX_MEMORY                                  maximum amount of RAM in GB
  --execution-provider {cpu} [{cpu} ...]                   available execution provider (choices: cpu, ...)
  --execution-threads EXECUTION_THREADS                    number of execution threads
```

I installed the dependencies for Apple Silicon and run deep-live-com with `python run.py --execution-provider coreml`

Thanks for the help and the awesome project!

**Comment by Retha23** [comment]
I could only make the max memory up to 7 even though my machine has 16. It doesn't allow me to go further. So, you could try it. 

For a better performance, please download inswapper_216.onnx (no fp16) from huggingface, rename it to inswapper_216.fp16.onnx, and replace this file with the one in the modules folder. 

Also, instead of installing onnxruntime 1.13.1, try 1.16.3:

```
pip uninstall onnxruntime onnxruntime-silicon
pip install onnxruntime-silicon==1.13.1
```

After these steps, you should be getting +10 fps, and no temperature issues. It still does not fully utilize the GPU cores though. Hoping to get a fix for it.

**Comment by lulu3243** [comment]
Retha can u give u discord to helpme please? my discord is bruxamadooeste add me
