### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Noragami13** [hacksider/Deep-Live-Cam#509]
![photo_2024-08-30_23-33-53](https://github.com/user-attachments/assets/8c6c9dad-5b42-4557-b622-c7c535f83efa)
Hello, when I launch a live camera, or try to remake a video, it gives me this error, and the camera is just black. Please help me, I don't understand anything about this, it took me 5 hours to get it installed, but it doesn't work anyway. Thanks

**Comment by Noragami13** [comment]
![image](https://github.com/user-attachments/assets/443fa6ef-5ee7-4b68-825c-db65713b8d2a)
The face is in place.

**Comment by bamjun** [comment]
change the file name to english

**Comment by Noragami13** [comment]
> change the file name to english

Thank you for your help. Everything works.

**Comment by margo2130** [comment]
> change the file name to english

can you help me, i am trying to extend this image and get the same error:
'NoneType' object has no attribute 'shape'
but the picture name is english already.
[fdasfadsfadsfadsfads.json](https://github.com/user-attachments/files/17128777/fdasfadsfadsfadsfads.json)

i share the work flow.

**Comment by Zhanos24** [comment]
change the file name to english！that really helps！

**Comment by robji15** [comment]
搞定了，哈哈，原来是你导入的人脸图片路径不能包含中文

**Comment by antonioii** [comment]
The error is likely occurring because some paths (probably where the executable is located) contain special characters and/or spaces. To resolve this, one can either move the executable to a folder with a simple path that doesn’t include special characters or spaces (e.g., C:\Desktop\AI_Experiments), or use the "short" version of the path to execute the software. Most operating systems provide such short paths to avoid issues with special characters and spaces in critical operations:

- On Windows (Command Prompt): Navigate to the parent folder in the console and type "dir /x". This will list the short names for directories, which can then be used without errors. The short path might look something like "READT~1".

- On Linux: Use "ls -i" to get the inode number of the directory, then use "find . -inum <inode_number>" to find the folder name in a format that avoids special characters or spaces.

Following these steps should help avoid path-related issues and allow the program to run properly.
