### ISSUE TITLE
AMD GPU Rrom Linux Support

### ISSUE THREAD

**Issue by harshb20** [hacksider/Deep-Live-Cam#513]
For people willing to accelerate this using rocm in linux, any way to make that GPU acceleration happen?

**Comment by NeuroDonu** [comment]
you can use torch cpu and onnxruntime from rocm (although in principle you can install torch with rocm support, but imho - it's not necessary). after that you just have to look through the list of available devices and choose rocm (maybe it will be called like that, I won't tell you exactly - I have no experience with ROCM, because I use NVIDIA).
