### ISSUE TITLE
Deep-Live-Cam-main\models\inswapper_128.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by kushdongX** [hacksider/Deep-Live-Cam#610]
when i launch, i got this error " sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\JOHNJ\Desktop\Deep-Live-Cam-main\Deep-Live-Cam-main\models\inswapper_128.onnx failed:Protobuf parsing failed." 
Even if i launch it with python run.py or with the CUDA arguments.
I tried even the the replacement version of the model, and those upgrades: "pip install onnxruntime --upgrade" "pip install protobuf --upgrade". Thank you for your time

**Comment by junweipan** [comment]
It is because the inswapper_128.onnx too large to load, you can follow this guide:
https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original

1, download the inswapper_128.onnx manually
2, put this model to your_path/models

**Comment by smallLil** [comment]
same question

**Comment by hacksider** [comment]
> It is because the inswapper_128.onnx too large to load, you can follow this guide: https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original
> 
> 1, download the inswapper_128.onnx manually 2, put this model to your_path/models

Just follow what @junweipan have said :)

**Comment by kushdongX** [comment]
ty sir, it worked!
