### ISSUE TITLE
live fps configuration advice

### ISSUE THREAD

**Issue by saske88** [hacksider/Deep-Live-Cam#722]
hi i'm looking for a pc configuration to create deepfake live with 15-20fps. can someone give me advice?

**Comment by D-a-r-n-o-l-d** [comment]
i got like 24 with an hp victus, $800 laptop

also this is defo not the place to ask this, please close this issue.

**Comment by D-a-r-n-o-l-d** [comment]
i've since moved to linux but when i was on windows 10 I got like 24 fps without face enhancer, now that i've moved over im having issues getting CUDA working so im getting like 2 as well.
the victus i use has a 4050 mobile but you can get a newer model for the same price with a 4060 mobile.
my cpu is a Ryzen 7 7840HS w/ Radeon 780M Graphics

**Comment by saske88** [comment]
@D-a-r-n-o-l-d hi I understand, maybe I explained myself wrong, I meant live enhancer how can I do more fps?

**Comment by D-a-r-n-o-l-d** [comment]
Aside from getting significantly better hardware, I don't think there's much you can do.

however if you want the live webcam to look more realistic, I'd make the input footage look worse instead of turning on face enhancer.
