### ISSUE TITLE
I'm the subscriber, but they don't even reply to my emails when I encounter an issue.

### ISSUE THREAD

**Issue by kitcendo** [hacksider/Deep-Live-Cam#731]
I'm the subscriber, but they don't even reply to my emails when I encounter an issue.

yeah, that what they do.

**Comment by hacksider** [comment]
Hi there,

You have refunded and I keep on telling you that you can go to github if you have any questions since that email was supposedly for those who have issues with gumroad. I have answered some of your queries though.

Regards, Ken

**Comment by kitcendo** [comment]
Please double-check carefully. I subscribed again since the 17th.







ในวันที่ อ. 22 ต.ค. 2024 08:39 น. Kenneth Estanislao <
***@***.***> เขียนว่า:

**Comment by hacksider** [comment]
I have replied to your inquiry now. I have to ignore you before since I keep on telling you to proceed here after many replies and I have to prioritize those who have subscribed.

Here's a trail of our email threads before just to ensure everyone that I always answer emails (even after refunded).
![image](https://github.com/user-attachments/assets/9ccb0407-670b-4609-b134-ff93f0aa4328)
