### ISSUE TITLE
MacOS version?

### ISSUE THREAD

**Issue by Xayaan** [hacksider/Deep-Live-Cam#801]
Any idea when MacOS version will be released?

**Comment by hacksider** [comment]
You can actually use the open source to build it for mac. As of now I don't have any plans of doing a gumroad edition for mac since most people already complain about the low fps they are getting even with dedicated GPU. I can already imagine everyone doing disputes/refunds because they cant reach beyond 10fps 😅

**Comment by antidote421** [comment]
> You can actually use the open source to build it for mac. As of now I don't have any plans of doing a gumroad edition for mac since most people already complain about the low fps they are getting even with dedicated GPU. I can already imagine everyone doing disputes/refunds because they cant reach beyond 10fps 😅

Did you change your mind, because you can buy macOS version on gumroad now?

**Comment by hacksider** [comment]
> > You can actually use the open source to build it for mac. As of now I don't have any plans of doing a gumroad edition for mac since most people already complain about the low fps they are getting even with dedicated GPU. I can already imagine everyone doing disputes/refunds because they cant reach beyond 10fps 😅
> 
> Did you change your mind, because you can buy macOS version on gumroad now?

It's still open source, but you can get it on gumroad as well. Nothing much has changed except of its availability on gumroad which is still an option. Either way, I don't see any issues with that.
